echo "--------------------------------"
echo "--------------------------------"
echo "--------------------------------"
echo "source /usr/local/oecore-x86_64/environment-setup-cortexa8hf-vfp-neon-oe-linux-gnueabi"
echo "--------------------------------"
echo "--------------------------------"
echo "--------------------------------"
source /usr/local/oecore-x86_64/environment-setup-cortexa8hf-vfp-neon-oe-linux-gnueabi
echo "--------------------------------"
echo "--------------------------------"
echo "--------------------------------"
echo "./configure --host=x86_64-oesdk-linux --target=arm-oe-linux-gnueabi"
echo "--------------------------------"
echo "--------------------------------"
echo "--------------------------------"
./configure --host=x86_64-oesdk-linux --target=arm-oe-linux-gnueabi
echo "--------------------------------"
echo "--------------------------------"
echo "--------------------------------"
echo "make"
echo "--------------------------------"
echo "--------------------------------"
echo "--------------------------------"
make
